extends Node3D
## Visual-only curls around the blade and lingering ridges around cleared paths.
## There is no airborne sheet, forward jet or distant landing point.

const Impact := preload("res://scripts/water_jet_impact.gd")
const Trail := preload("res://scripts/squeegee_water_trail.gd")
const HEAD_HALF := Vector2(0.34, 0.075)
const REFERENCE_AREA_RATE := 0.65

@export_range(0.06, 0.24, 0.005) var splash_reach := 0.17
@export_range(0.025, 0.11, 0.005) var splash_height := 0.085

var impact: Node3D
var trail: Node3D
var footprint: RefCounted
var enabled := false
var feeding := false
var unpresented_feed := false
var clock_seconds := 0.0
var deadline := 0.0
var emitted_strokes := 0
var removed_water := 0.0
var surface_texture: ImageTexture
var pixel_area := 0.0
var contact_position := Vector3.ZERO
var heading := Vector3.FORWARD
var movement_speed := 0.0
var power := 0.0

func _ready() -> void:
	set_process(false)

func setup(rug_footprint: RefCounted, surface_pixels: PackedByteArray, mask_size: Vector2i, soil: Node = null) -> void:
	assert(impact == null, "Allocate the perimeter splash pool once")
	footprint = rug_footprint
	pixel_area = 2.0 * 3.32 / float(mask_size.x * mask_size.y)
	# Immutable surface silhouette, not a second simulation/wetness texture.
	var pixels := surface_pixels.duplicate()
	for i in pixels.size():
		pixels[i] = 255 if pixels[i] != 0 else 0
	surface_texture = ImageTexture.create_from_image(Image.create_from_data(mask_size.x, mask_size.y, false, Image.FORMAT_L8, pixels))
	impact = Impact.new()
	impact.name = "HeadPerimeterSplashAndDroplets"
	add_child(impact)
	impact.setup(footprint, surface_texture)
	if soil != null:
		trail = Trail.new()
		trail.name = "ClearedPathWaterRidgeAndRunoff"
		add_child(trail)
		trail.setup(soil, surface_texture)
	reset()

func set_enabled(value: bool) -> void:
	reset()
	enabled = value

func reset() -> void:
	feeding = false
	unpresented_feed = false
	clock_seconds = 0.0
	deadline = 0.0
	emitted_strokes = 0
	removed_water = 0.0
	power = 0.0
	movement_speed = 0.0
	heading = Vector3.FORWARD
	contact_position = Vector3.ZERO
	if is_instance_valid(impact): impact.reset()
	if is_instance_valid(trail): trail.reset()
	set_process(false)

func end_stroke() -> void:
	feeding = false
	unpresented_feed = false
	# Existing little curls/droplets settle at the last contact position. No
	# new supply is generated by release, a dry pass or pointer inactivity.
	set_process((is_instance_valid(impact) and impact.is_alive()) or (is_instance_valid(trail) and trail.is_alive()))

func feed_stroke(from: Vector3, to: Vector3, elapsed: float, removed: float, facing: Vector3 = Vector3.ZERO, speed: float = -1.0) -> void:
	var displacement := Vector3(to.x - from.x, 0.0, to.z - from.z)
	if not enabled or not is_instance_valid(impact) or removed <= 0.0001 or displacement.length_squared() < 0.00001:
		end_stroke()
		return
	var seconds := clampf(elapsed if elapsed > 0.0 else 1.0 / 60.0, 1.0 / 240.0, 0.08)
	var planar_facing := Vector3(facing.x, 0.0, facing.z)
	heading = planar_facing.normalized() if planar_facing.length_squared() > 0.0001 else displacement.normalized()
	movement_speed = clampf(speed if speed >= 0.0 else displacement.length() / seconds, 0.0, 2.5)
	var target_power := clampf(removed * pixel_area / seconds / REFERENCE_AREA_RATE, 0.015, 1.0)
	power = lerpf(power, target_power, 1.0 - exp(-seconds / 0.065)) if feeding else target_power
	# The incoming height already accounts for a blade overlapping the rug.
	# Center the rectangle on that contact; never add the old front-lip offset.
	contact_position = to
	feeding = true
	unpresented_feed = true
	deadline = clock_seconds + clampf(seconds * 1.4, 0.025, 0.075)
	emitted_strokes += 1
	removed_water += removed
	if is_instance_valid(trail): trail.notify_extraction(contact_position, removed)
	set_process(true)

func _process(delta: float) -> void:
	if not is_instance_valid(impact): return
	var step := clampf(delta, 0.0, 0.1)
	clock_seconds += step
	# A funded input sample must reach the renderer once even when the next
	# frame arrives after the short idle timeout (e.g. a 100 ms frame hitch).
	if feeding and clock_seconds > deadline and not unpresented_feed:
		feeding = false
	impact.rect_reach = splash_reach
	impact.rect_height = splash_height
	impact.update_rect_contact(feeding, contact_position, HEAD_HALF, heading, power, step)
	if is_instance_valid(trail): trail.advance(step)
	unpresented_feed = false
	set_process(feeding or impact.is_alive() or (is_instance_valid(trail) and trail.is_alive()))

func debug_stats() -> Dictionary:
	var stats: Dictionary = impact.debug_stats() if is_instance_valid(impact) else {}
	return {
		"active_sheets": 0, # Explicit regression guard: never recreate the old column.
		"active_splashes": int(is_instance_valid(impact) and impact.patch.visible),
		"feeding_splashes": int(feeding),
		"active_edges": int(stats.get("active_edges", 0)),
		"heading": heading, "movement_speed": movement_speed,
		"contact_position": contact_position, "power": power,
		"emitted_strokes": emitted_strokes, "removed_water": removed_water,
		"processing": is_processing(), "impact": stats,
		"trail": trail.debug_stats() if is_instance_valid(trail) else {},
	}
